const gallery = [
  {
    id: 0,
    title: 'Covid Kush',
    description: 'Chrystally orange hairy goodness',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/hybrid1.jpg',
    linkURL: 'https://unsplash.com/photos/h7REcabpVHY',
    credit: 'Avery Meeker',
    creditURL: 'https://unsplash.com/photos/h7REcabpVHY',
  },
  {
    id: 1,
    title: 'Northern Lights',
    description: 'Long Orange Hairs',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/hybrid2.jpg',
    linkURL: 'https://unsplash.com/photos/NXrRfCuGKSI',
    credit: 'Camila Serey',
    creditURL: 'https://unsplash.com/photos/NXrRfCuGKSI',
  },
  {
    id: 2,
    title: 'Pineapple Express',
    description: 'Super Dense Green Nug',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/hybrid3.jpg',
    linkURL: 'https://unsplash.com/photos/acvgrEgivMM',
    credit: 'Ndispensable',
    creditURL: 'https://unsplash.com/photos/acvgrEgivMM',
  },
  {
    id: 3,
    title: 'Maui Wowie',
    description: 'Couple Grams of Dank',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/hybrid4.jpg',
    linkURL: 'https://unsplash.com/photos/d4ihF4uFvK4',
    credit: 'Ndispensable',
    creditURL: 'https://unsplash.com/photos/d4ihF4uFvK4',
  },
  {
    id: 4,
    title: 'Lemon Haze',
    description: 'Few Super Juicy Chrystally Nugzzz',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/indica1.jpg',
    linkURL: 'https://unsplash.com/photos/2rW8lq0NgPU',
    credit: 'Avery Meeker',
    creditURL: 'https://unsplash.com/photos/2rW8lq0NgPU',
  },
  {
    id: 5,
    title: 'Sour Tangie',
    description: 'Red Hairzz',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/indica2.jpg',
    linkURL: 'https://unsplash.com/photos/7-VhhCfFtzk',
    credit: 'Ndispensable',
    creditURL: 'https://unsplash.com/photos/7-VhhCfFtzk',
  },
  {
    id: 6,
    title: 'Peanut Butter Breathe',
    description: 'Green Crack',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/indica3.jpg',
    linkURL: 'https://unsplash.com/photos/jC1btnZp1-w',
    credit: 'Ndispensable',
    creditURL: 'https://unsplash.com/photos/jC1btnZp1-w',
  },
  {
    id: 7,
    title: 'LA Confidential',
    description: 'Container Spillage Of The Herb',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/indica4.jpg',
    linkURL: 'https://unsplash.com/photos/-y7YQD56SMg',
    credit: 'Ndispensable',
    creditURL: 'https://unsplash.com/photos/-y7YQD56SMg',
  },
  {
    id: 8,
    title: 'Sour Diesel',
    description: 'Small Little Cute Nuggy',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/sativa1.jpg',
    linkURL: 'https://unsplash.com/photos/Ld9FQlMez8g',
    credit: 'Christina Winter',
    creditURL: 'https://unsplash.com/photos/Ld9FQlMez8g',
  },
  {
    id: 9,
    title: 'Afghani Kush',
    description: 'Super Dense Purple Nuggyz',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/sativa2.jpg',
    linkURL: 'https://unsplash.com/photos/d_3Yc55MAr8',
    credit: 'Christina Winter',
    creditURL: 'https://unsplash.com/photos/d_3Yc55MAr8',
  },
  {
    id: 10,
    title: 'Blue Cheese',
    description: 'Super Green Crack',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/sativa3.jpg',
    linkURL: 'https://unsplash.com/photos/JkXxzThO54U',
    credit: 'Ndispensable',
    creditURL: 'https://unsplash.com/photos/JkXxzThO54U',
  },
  {

    id: 11,
    title: 'Wedding Cake',
    description: 'Quarter oz',
    height: 500,
    width: 500,
    pathURL: 'images/edited/small/sativa4.jpg',
    linkURL: 'https://unsplash.com/photos/iGqTOMbzLws',
    credit: 'Ndispensable',
    creditURL: 'https://unsplash.com/photos/iGqTOMbzLws',
  }
];

module.export = gallery;